# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuscaCompleta():
  
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("detach", True) # Opção detach é melhor
    self.driver = webdriver.Chrome(options=options)
    
    self.vars = {}
  
  #def teardown_method(self, method):
    #self.driver.quit()
  
  #@pytest.fixture
  def test_BuscaCompleta(self):
    # Test name: BuscaCompleta
    # Step # | name | target | value
    # 1 | open | http://localhost:8080/browse-users.php | 
    self.driver.get("http://localhost:8080/browse-users.php")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | id=nome | 
    self.driver.find_element(By.ID, "nome").click()
    # 4 | type | id=nome | Jorge
    self.driver.find_element(By.ID, "nome").send_keys("Ma")
    
    '''
    # 5 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 6 | type | id=email | jorgeteste@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("RogerioCoimbra@gmail.com")
    # 7 | click | id=telefone | 
    self.driver.find_element(By.ID, "telefone").click()
    # 8 | type | id=telefone | 333
    self.driver.find_element(By.ID, "telefone").send_keys("333")
    # 9 | click | id=df | 
    self.driver.find_element(By.ID, "df").click()
    # 10 | type | id=df | 2021-01-01
    self.driver.find_element(By.ID, "df").send_keys("2021-01-01")
    # 11 | click | id=dt | 
    self.driver.find_element(By.ID, "dt").click()
    # 12 | type | id=dt | 2025-01-01
    self.driver.find_element(By.ID, "dt").send_keys("2025-01-01")
    '''
    
    # 13 | click | css=#submit > .fa | 
    self.driver.find_element(By.CSS_SELECTOR, "#submit > .fa").click()
  
